DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS chat;
DROP TABLE IF EXISTS message;

CREATE TABLE IF NOT EXISTS user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    realId INTEGER NOT NULL,
    username TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS chat(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userId INTEGER NOT NULL,
    FOREIGN KEY(userId) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS message(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sender VARCHAR,
    content TEXT NOT NULL,
    sentAt DATETIME,
    readAt DATETIME,
    chatId INTEGER NOT NULL,
    FOREIGN KEY (chatId) REFERENCES chat(id) ON DELETE CASCADE
);